#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; IMAGE="dokku/$APP"; HOSTNAME=$(hostname -f);

echo "-----> Setting up config"
echo APP
#if test -z "$TIMEZONE"; then
#    TIMEZONE=$( cat /etc/timezone )
#fi

#id=$(docker run -d $IMAGE /bin/bash -c "ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime")
#test $(docker wait $id) -eq 0
#docker commit $id $IMAGE > /dev/null
echo "-----> End Setup"
