#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; IMAGE="dokku/$APP"; HOSTNAME=$(hostname -f);

echo "-----> Setting up DB Config"
if test -z "$TIMEZONE"; then
    TIMEZONE=$( cat /tmp/config.properties )
fi

id=$(cat /tmp/config.properties |  docker run -i -a stdin $IMAGE /bin/bash -c "cat > /app/config.properties")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
echo "-----> DB Config is set to"
echo "$TIMEZONE"
